# Generated by Django 4.0.4 on 2022-05-10 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=100, null=True)),
                ('lon', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('timeZone', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clouds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(blank=True, null=True)),
                ('feels_like', models.IntegerField(blank=True, null=True)),
                ('temp_min', models.IntegerField(blank=True, null=True)),
                ('temp_max', models.IntegerField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('sunrise', models.CharField(blank=True, max_length=100, null=True)),
                ('sunset', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(default='Clear', max_length=100)),
                ('description', models.CharField(default='Clear Sky', max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('deg', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='city_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.IntegerField(blank=True, default=1000, null=True)),
                ('view', models.CharField(blank=True, max_length=200, null=True)),
                ('cod', models.IntegerField(blank=True, null=True)),
                ('base', models.CharField(blank=True, max_length=100, null=True)),
                ('dt', models.CharField(blank=True, max_length=100, null=True)),
                ('City', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.city')),
                ('Clouds', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.clouds')),
                ('Main', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.main')),
                ('Weather', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.weather')),
                ('Wind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.wind')),
                ('sys', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.sys')),
            ],
        ),
    ]
